### ISSUE TITLE
add more than one name

### ISSUE THREAD

**Issue by Lorac** [jdavis/latex-homework-template#1]
I would like to be able to add more than one name in authors for teamed assignements.

**Comment by jdavis** [comment]
That sounds good.

A few questions first:
1. What happens when you put multiple names in the author field that doesn't work?
2. Based on the above, what would you prefer to happen?

**Comment by Lorac** [comment]
1. It appends with the current name with no space, I tried with \n, \, \newline, nothing worked.
2. One line per name pretty much
