### ISSUE TITLE
Remove PDF from version control

### ISSUE THREAD

**Issue by jppgks** [jdavis/latex-homework-template#5]
What's the goal of having the compiled .pdf file under version control?

**Comment by jdavis** [comment]
So people can see what the output looks like.

**Comment by jppgks** [comment]
Don't you use the screenshots in the readme for that purpose?

**Comment by jdavis** [comment]
I think both provide value. The pngs are for a quick overview because people that won't be willing to download a PDF and are just skimming to see if this template works for them. Then there are some people that actually want to see the PDF output.
