### ISSUE TITLE
Latex Compiling Error

### ISSUE THREAD

**Issue by benyanke** [jdavis/latex-homework-template#6]
I realize this is probably me setting it up wrong, but when I try and run:  `latexmk homework.tex` it stops and says:
```
[2]
Underfull \hbox (badness 10000) in paragraph at lines 217--220



! LaTeX Error: Unknown float option `e'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.225     \begin{figure}[here]

```

I'm relatively new to LaTeX, but I really hope to begin using it. What am I missing here?

**Comment by jdavis** [comment]
What version of LaTeX are you using?

**Comment by GTres** [comment]
Hi,
How do you include a listing of code?

**Comment by lemonad** [comment]
I had the same problem and I think `[here]` should be `[h]`?

**Comment by jdavis** [comment]
I've changed it from `figure[here]` to `figure[h]`. Turns out old versions of LaTeX would just silently ignore the invalid options. Newer versions no longer do this: http://tex.stackexchange.com/questions/256172/latex-error-unknown-float-option-d

Let me know if you continue to have issues.
